### ISSUE TITLE
Error: WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by briankl** [shawnLiujianwei/puppeteer-lambda#13]
I get this error exactly every other time I run the lambda. Only running the code below.

````
(async () => {
    const browser = await puppeteer.getBrowser({
      headless: true
    });
    await browser.close();
    callback(null, { test: 'hello' });
  })();
````

````
START RequestId: 35bb8dae-fe2c-11e8-be11-63fb084f25a3 Version: $LATEST
2018-12-12T16:37:26.901Z	35bb8dae-fe2c-11e8-be11-63fb084f25a3	Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/var/task/node_modules/ws/lib/websocket.js:322:19)
    at WebSocketTransport.send (/var/task/node_modules/puppeteer/lib/WebSocketTransport.js:57:14)
    at Connection.send (/var/task/node_modules/puppeteer/lib/Connection.js:71:21)
    at Browser._getVersion (/var/task/node_modules/puppeteer/lib/Browser.js:267:29)
    at Browser.version (/var/task/node_modules/puppeteer/lib/Browser.js:242:32)
    at Browser.<anonymous> (/var/task/node_modules/puppeteer/lib/helper.js:145:23)
    at isBrowserAvailable (/var/task/node_modules/puppeteer-lambda/src/index.js:53:29)
    at _getBrowser (/var/task/node_modules/puppeteer-lambda/src/index.js:12:41)
    at Object.exports.getBrowser (/var/task/node_modules/puppeteer-lambda/src/index.js:47:11)
    at /var/task/index.js:15:37
    at exports.handler (/var/task/index.js:34:5)
END RequestId: 35bb8dae-fe2c-11e8-be11-63fb084f25a3
REPORT RequestId: 35bb8dae-fe2c-11e8-be11-63fb084f25a3	Duration: 20020.45 ms	Billed Duration: 20000 ms 	Memory Size: 1024 MB	Max Memory Used: 215 MB	
2018-12-12T16:37:46.895Z 35bb8dae-fe2c-11e8-be11-63fb084f25a3 Task timed out after 20.02 seconds
````

**Comment by briankl** [comment]
We're also storing headless_shell.tar.gz on S3. It seems to be setup correctly, and as I said it works exactly every other time.

**Comment by blkdr** [comment]
> **browser.close()**
>
> Closes Chromium and all of its pages (if any were opened). **The Browser object itself is considered to be disposed and cannot be used anymore**.

[Source](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#browserclose)

In your function already deployed to lambdas If you call your function twice in a couple of seconds its highly probably that Amazon uses the previous context where the browser has been closed and run a timeout exception.

My fix is to open a new page, visit my desired page and save it as PDF and then close only the page leaving the browser instance open.

```javascript
(async () => {
    const browser = await puppeteer.getBrowser({
      headless: true
    });
    const page = await browser.newPage(); // Open a new tab
    await page.goto(MY_URL, { waitUntil: 'networkidle0' }); // Use the tab to visit my desired page
    const buffer = await page.pdf({ format: 'Letter' }); // Save it as buffer to use it as callback
    await page.close(); // Close the tab instead of closing the browser
    // await browser.close(); Do not close the browser
    callback(null, { test: 'hello' }); // Run your callback
})();
```

In my local environment I manage the stop (aka Ctrl + C) with a callback that closes the browser.

In Lambdas the browser is not closed until Amazon deletes the instance.

**Comment by shawnLiujianwei** [comment]
@blkdr  you're right , i just run some test to confirm this. thanks . i will make the changes to add disposer to the browser object
