### ISSUE TITLE
Assertion error

### ISSUE THREAD

**Issue by BTruer** [shawnLiujianwei/puppeteer-lambda#2]
Hello,

I am attempting to use your package here. However I get this error:

`{
  "errorMessage": "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"",
  "errorType": "AssertionError [ERR_ASSERTION]",
  "stackTrace": [
    "Console.assert (console.js:194:23)",
    "Function.launch (/var/task/node_modules/puppeteer/lib/Launcher.js:97:15)",
    "<anonymous>"
  ]
}`

In particular this is the stack trace with the debug flag on
`TypeError: Cannot read property 'version' of null
    at _callee3$ (~/node_modules/puppeteer-lambda/src/index.bundle.js:210:40)
    at tryCatch (~/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (~/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (~/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (~/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at ~/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (~/node_modules/core-js/library/modules/_export.js:36:28)
    at ~/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
    at isBrowserAvailable (~/node_modules/puppeteer-lambda/src/index.bundle.js:235:22)`

It looks like the isBrowesrAvailable is not handling the case when it gets a false and looks for a version.

Thank you

**Comment by shawnLiujianwei** [comment]
@BTruer  
`{ "errorMessage": "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"", "errorType": "AssertionError [ERR_ASSERTION]", "stackTrace": [ "Console.assert (console.js:194:23)", "Function.launch (/var/task/node_modules/puppeteer/lib/Launcher.js:97:15)", "<anonymous>" ] }` 
means you don't have local chrome in you node_modules, check details from (Puppeteer)[https://github.com/GoogleChrome/puppeteer]

and i made some changes to ensure you only need download the `custom chrome` when you prepare the package for lambda. you can check the latest (REAMDE.md)[https://github.com/shawnLiujianwei/puppeteer-lambda/blob/master/README.md]

**Comment by tomgallagher** [comment]
I've just had a go using this as well. 

I have exactly the same error message.

Installed with puppeteer_skip_chromium_download=true

Node 8.1.0

Environment variable set CUSTOM_CHROME to true.

Any ideas?

**Comment by tomgallagher** [comment]
Just had a look into this.

Puppeteer is failing at this point (/var/task/node_modules/puppeteer/lib/Launcher.js:97:15)

```
let chromeExecutable = options.executablePath;
if (typeof chromeExecutable !== 'string') {
      const browserFetcher = new BrowserFetcher();
      const revisionInfo = browserFetcher.revisionInfo(ChromiumRevision);
      console.assert(revisionInfo.local, `Chromium revision is not downloaded. Run "npm install" or "yarn install"`);
      chromeExecutable = revisionInfo.executablePath;
}
```
There's no executable path being passed to Chrome, and that it because we're falling back to the version where Puppeteer has installed Chromium (when Puppeteer-Lambda rightly does not install it), because of this:

Looking at puppeteer-lambda, puppeteer-lambda/src/index.js, line 17

`if (process.env.CUSTOME_CHROME || (process.env.CHROME_BUCKET && process.env.CHROME_KEY)) {`

That's a typo. Hopefully that gets it working.

Sorry to get so involved, I'd just love to get this working and your approach is the cleanest I have seen so far.

Tom

**Comment by shawnLiujianwei** [comment]
@tomgallagher  which version you are using , pls use 1.0.9 which i fix the typo and separate the chrome binary to another repo. 

thanks to figure out the typo

**Comment by tomgallagher** [comment]
Yes I'm using "puppeteer-lambda": "^1.0.10".

So there's still this assertion error?

**Comment by tomgallagher** [comment]
OK the typo fixed the assertion error. Now there's a problem with collecting the local version of chrome.

**Comment by shawnLiujianwei** [comment]
@tomgallagher   pls have a look the [README.md](https://github.com/shawnLiujianwei/puppeteer-lambda/blob/master/README.md#packaging--deploy)

**Comment by tomgallagher** [comment]
Yes. I have. Have you actually tested your code on Amazon?

**Comment by tomgallagher** [comment]
Ah. That I may not have done. I had a tar.gz file in the folder but I don't think it was decompressed. Probably a good idea to add this to README.md:

BEFORE INSTALLING PACKAGE

Add a file callled .npmrc at the same level as your package json.

In this file, put:

```
puppeteer_skip_chromium_download=true
CUSTOM_CHROME=true
```
Then when you download, you see a message from Puppeteer saying that the Chromium download has been skipped.

**Comment by shawnLiujianwei** [comment]
@tomgallagher  can you do a pull request ? and i will prepare one sample to run it in lambda

**Comment by shawnLiujianwei** [comment]
@tomgallagher  i tested , seems the chrome binary it's broken , my  lambda now is using the one i uploaded to my s3 , so did't have this problem.  i have replaced the chrome binary (version 67) and and also fix the typo , please use latest version 1.0.11 . sorry for the mistake

**Comment by shawnLiujianwei** [comment]
here is my sample:

handler.js
`const lambdaPuppeteer = require('puppeteer-lambda');
exports.handler = async (event, context) => {
    try {
        const url = event.url || 'https://www.google.com';
        const browser = await lambdaPuppeteer.getBrowser();
        const page = await browser.newPage();
        await page.goto(url);
        const title = await page.title();
        context.succeed(JSON.stringify({url, title}));

    } catch (err) {
        console.log(err.message);
        context.fail(err.message || err.stack || err);
    }
}`

package.json
`{
  "name": "ls",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "puppeteer-lambda": "^1.0.11"
  }
}`

deploy.sh

`cp serverless.yml ./dist/
cp package.json ./dist/
cp -r handler.js ./dist/
cd dist && PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true CUSTOM_CHROME=true yarn --production`

the `serverless.yml` is used for [Serverless](https://github.com/serverless/serverless)

**Comment by tomgallagher** [comment]
@shawnLiujianwei 

No worries. Another thing I've been thinking about - your approach may well be superior to other serverless chrome options because it assigns an executable path in the Lambda function. So a new version of Chrome is instantiated on each call to Lambda. This may be slower but means that you do not have complications associated with two concurrent calls to the Lambda function.

**Comment by shawnLiujianwei** [comment]
I think you are right, if you want reuse the chrome, i think the easier way is send more urls to one lambda, also you can have a look chromeless https://github.com/graphcool/chromeless , after you deploy it to lambda you will get ine url to use it,but puppeteer has more options to control the browser, seems chromeless planned to use puppeteer too

**Comment by tomgallagher** [comment]
When you build your package before updating its version on NPM, do you automate the process of checking which version of Chrome is being used by Puppeteer, then create that binary build, save it to the chrome folder, etc. Is that even possible?

**Comment by shawnLiujianwei** [comment]
No, i didn't di that, normally we don't need change chrome version unkess you need the new features.  If you need you can build it manually

**Comment by tomgallagher** [comment]
Yes, I understand that. I'm just saying that, given you have a clean, fairly transparent method of employing Puppeteer on Lambda, your package could benefit. Puppeteer makes a big deal of saying 'this version is tested with xxx version of Chrome'. If you want to become the method of choice for using Puppeteer on Lambda, you would benefit from saying 'puppeteer/lambda has been tested with xxx version of Puppeteer and always installs the correct version of Chrome.

**Comment by tomgallagher** [comment]
It's just an automation process to ensure that your internal Puppeteer version is always latest stable and the Chrome version matches. Otherwise, if people start to adopt your package, you will have lots of enquiries about why some new Puppeteer feature is not available / not working or why Puppeteer is reporting errors in its interaction with Chrome.

**Comment by tomgallagher** [comment]
All the info for this is in Puppeteer package.json which I guess you could get from github. The only thing I don't know is whether it is possible to automate a Lambda build of specific version of Chrome.

**Comment by tomgallagher** [comment]
https://stackoverflow.com/questions/15957529/can-i-install-a-npm-package-from-javascript-running-in-node-js

**Comment by shawnLiujianwei** [comment]
understand , thanks for that . the lambda chrome binary was build from ec2 , let me try to docker to build that rather than in ec2 instance . then i can put the Dockerfile in this project so that user can build the required version

**Comment by shawnLiujianwei** [comment]
@tomgallagher   Does it work now ? will close the issue

**Comment by tomgallagher** [comment]
yes close it.

**Comment by linpekka** [comment]
I'm testing this and run into the same issue, I'm thinking it may be that different chromium revisions are needed for different versions of puppeteer? Which version of puppeteer was expected when you generated the chome version that is included? I have verified that I have a version of chrome in the dist package.
