### ISSUE TITLE
Missing required key 'Bucket' in params

### ISSUE THREAD

**Issue by ratkorle** [shawnLiujianwei/puppeteer-lambda#5]
Hi. I am using puppeteer-lambda. I set up CUSTOM_CHROME as a lambda variable, but when i try to execute the function I have this error. Can anyone please tell me where to look or what does it means:
`2018-10-08T09:35:51.790Z	8ae5a981-cadd-11e8-bbbf-c7ce2c26cd5d	{ MissingRequiredParameter: Missing required key 'Bucket' in params
    at ParamValidator.fail (/var/task/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/var/task/node_modules/aws-sdk/lib/param_validator.js:61:14)
    at ParamValidator.validateMember (/var/task/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/var/task/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:125:42)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at callNextListener (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:99:12)
    at /var/task/node_modules/aws-sdk/lib/event_listeners.js:85:9
    at finish (/var/task/node_modules/aws-sdk/lib/config.js:322:7)
    at /var/task/node_modules/aws-sdk/lib/config.js:340:9
    at EnvironmentCredentials.get (/var/task/node_modules/aws-sdk/lib/credentials.js:126:7)
    at getAsyncCredentials (/var/task/node_modules/aws-sdk/lib/config.js:334:24)
    at Config.getCredentials (/var/task/node_modules/aws-sdk/lib/config.js:354:9)
    at Request.VALIDATE_CREDENTIALS (/var/task/node_modules/aws-sdk/lib/event_listeners.js:80:26)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:18)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:81:10)
  message: 'Missing required key \'Bucket\' in params',
  code: 'MissingRequiredParameter',
  time: 2018-10-08T09:35:51.788Z }`

**Comment by shawnLiujianwei** [comment]
@ratkorle  did you run the install command like `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true CUSTOM_CHROME=true yarn add puppeteer-lambda
` ?  if so , it should works , and you can check the folder `node_modules/puppeteer-lambda` , you should see folder `chrome`

**Comment by ratkorle** [comment]
I run that command. I set up custom-chrome (capitals) failed, then i tried chrome_bucket amnd chrome_key. But still the same error.
Missing required key 'Bucket' params
Please help me I lost 2 days

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ratkorle** [comment]
Or it doesnt run at all, the timeout pass by and throw err

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ratkorle** [comment]
It is getBrowser() problem

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
